Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2023-12, with the labels that each got.

#154 Added new sound emotions
  modular_RUtgmc/code/modules/mob/living/carbon/human/emote.dm
  modular_RUtgmc/includes.dm
  modular_RUtgmc/sound/misc/human_female_sneeze_1.ogg
  modular_RUtgmc/sound/misc/human_male_sneeze_1.ogg
  modular_RUtgmc/sound/voice/human_female_cry_1.ogg
  modular_RUtgmc/sound/voice/human_female_giggle_1.ogg
  modular_RUtgmc/sound/voice/human_female_moan_1.ogg
  modular_RUtgmc/sound/voice/human_female_sigh_1.ogg
  modular_RUtgmc/sound/voice/human_female_yawn_1.ogg
  modular_RUtgmc/sound/voice/human_male_cry_1.ogg
  modular_RUtgmc/sound/voice/human_male_giggle_1.ogg
  modular_RUtgmc/sound/voice/human_male_moan_1.ogg
  modular_RUtgmc/sound/voice/human_male_sigh_1.ogg
  modular_RUtgmc/sound/voice/human_male_yawn_1.ogg
Labels: Feature, Test Merge Candidate, Marine, Sound

#196 Attack_ghost() for clone vat.
  modular_RUtgmc/code/game/objects/machinery/cloning/cloning.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine, Coding

#187 Increases cloaker and drain smokes amount to 25 in vendors.
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Marine

#200 Neco Arc
  code/__DEFINES/~RUtgmc_defines/is_helpers.dm
  modular_RUtgmc/code/datums/emergency_calls/necoarc.dm
  modular_RUtgmc/code/datums/jobs/job/necoarc.dm
  modular_RUtgmc/code/datums/namepool.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/emote.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/human_species.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/species.dm
  modular_RUtgmc/includes.dm
  modular_RUtgmc/sound/voice/necoarc/Neco Muda muDa.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco NA NA NA.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco NA NA NA2.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco NA NA.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco NA.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco NANAA ANA Na.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco Sa Yesa 1.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco Sa Yesa 2.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco UUUUUUUHHHHNIIIAAAAA!!!!.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco bu buuu.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco dori dori dori.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco iiiiisAAAAA.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco niiiaaa.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco quiajuuubn.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco ungia!.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco yanyan yaan.ogg
  modular_RUtgmc/sound/voice/necoarc/Neco-Arc sound effect.ogg
  modular_RUtgmc/sound/voice/necoarc/NecoVIBIVII!!.ogg
  modular_RUtgmc/sound/voice/necoarc/Necojooooonoooooooo.ogg
Labels: Feature

#208 [NON-MODULAR] hivemind fix
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Fix, Xeno, Coding

#205 Возвращает Сюрту неуязвимость к огню
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Test Merge Candidate, Balance, Marine

#222 Hotfix 2
  code/__DEFINES/xeno.dm
  code/__DEFINES/~RUtgmc_defines/xeno.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  modular_RUtgmc/icons/Xeno/acid_pool.dmi
  modular_RUtgmc/icons/mob/hud.dmi
  modular_RUtgmc/icons/obj/clothing/gloves.dmi
  modular_RUtgmc/icons/obj/items/projectiles.dmi
Labels: Fix

#192 FC Updates
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/datums/skills.dm
  modular_RUtgmc/code/game/objects/items/radio/headset.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Test Merge Candidate, Balance, Marine

#215 Normandy
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/modules/shuttle/marine_dropship.dm
  modular_RUtgmc/code/datums/jobs/job/shipside.dm
  modular_RUtgmc/code/datums/jobs/job/sons_of_mars_shipside.dm
  modular_RUtgmc/code/game/objects/area/gelide_iv.dm
  modular_RUtgmc/code/game/objects/area/sulaco.dm
  modular_RUtgmc/code/game/objects/items/radio/intercom.dm
  modular_RUtgmc/code/game/turfs/closed.dm
  modular_RUtgmc/code/modules/power/lighting.dm
  modular_RUtgmc/code/modules/shuttle/marine_dropship.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Marine, Coding

#225 Fix oficer sword
  code/game/objects/items/storage/holsters.dm
  modular_RUtgmc/code/game/objects/items/storage/holsters.dm
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
  modular_RUtgmc/code/modules/projectiles/guns/revolvers.dm
  modular_RUtgmc/icons/obj/items/weapons.dmi
Labels: Fix, Marine

#219 Возвращение Бегемота
  modular_RUtgmc/code/_globalvars/lists/mobs.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  modular_RUtgmc/icons/Xeno/castes/behemoth.dmi
  modular_RUtgmc/includes.dm
Labels: Test Merge Candidate, Xeno, Sprites

#216 Updates valhalla weapon vendor
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix, Feature, Marine

#227 Возможный фикс крашей
  modular_RUtgmc/code/modules/projectiles/gun_attachables.dm
  modular_RUtgmc/code/modules/projectiles/guns/energy.dm
  modular_RUtgmc/code/modules/projectiles/guns/pistols.dm
  modular_RUtgmc/code/modules/projectiles/guns/revolvers.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
  modular_RUtgmc/code/modules/projectiles/guns/shotguns.dm
  modular_RUtgmc/code/modules/projectiles/guns/smgs.dm
  modular_RUtgmc/icons/Marine/attachments_64.dmi
Labels: Fix, Test Merge Candidate

#217 [SEMI-MODULAR] unfucks boiler
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Balance, Xeno

#214 Makes primo upgrades instant.
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/crash.dm
  code/modules/admin/topic.dm
  code/modules/events/hive_threat.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/evolution.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  modular_RUtgmc/includes.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Balance, Xeno

#224 Adds camera for miners.
  code/game/objects/machinery/miner.dm
  modular_RUtgmc/code/game/objects/machinery/camera/camera.dm
  modular_RUtgmc/code/game/objects/machinery/miner.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine, Coding

#232 Revert of mg27 and mg60 attachment nerfs
  modular_RUtgmc/code/modules/projectiles/guns/mounted.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine

#235 Ravager Screen Clean
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Test Merge Candidate, Xeno

#236 Bigger Hivestatus
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Test Merge Candidate, Xeno

#243 Поправки цен на примо
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance, Xeno

#245 Panther Nerf
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Balance, Xeno

#234 [MODULAR] Unfucks boiler, again
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Test Merge Candidate, Balance, Xeno

#242 behemoth primo buff
  code/__DEFINES/~RUtgmc_defines/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Test Merge Candidate, Balance, Xeno

#244 [FIX][MODULAR] Fix self harm for some weapons
  modular_RUtgmc/code/game/objects/items/tools/shovel_tools.dm
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
  modular_RUtgmc/code/modules/projectiles/gun_attachables.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Marine

#249 Normandy fixes
  _maps/~RUTGMC/shuttles/alamo.dmm
  _maps/~RUTGMC/shuttles/normandy.dmm
Labels: Fix

#255 Attack_ai for cloning console
  modular_RUtgmc/code/game/objects/machinery/cloning/cloning.dm
Labels: Marine, Quality of life

#256 Advanced tweezers for copsmans.
  code/__DEFINES/loadout.dm
Labels: Feature, Balance

#250 Attack_ai and theoretical fix for miner's camera.
  modular_RUtgmc/code/game/objects/machinery/miner.dm
Labels: Fix, Feature, Balance, Marine

#254 Ports the most needed feature from cm's.
  modular_RUtgmc/code/game/objects/structures/barricade.dm
  modular_RUtgmc/sound/machines/bonk.ogg
Labels: Feature, Xeno, Marine, Coding, Port

#261 Adds missed letter to advanced tweezers.
  code/__DEFINES/loadout.dm
Labels: Fix, Marine

#228 Химера
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/code/_globalvars/lists/mobs.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/ai/presets/xeno_presets.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/chimera/abilities_chimera.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/chimera/castedatum_chimera.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/chimera/chimera.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/icons/Xeno/actions.dmi
  modular_RUtgmc/icons/Xeno/castes/chimera.dmi
  modular_RUtgmc/includes.dm
Labels: Feature, Test Merge Candidate, Xeno, Sprites, Needs testing

#248 Allows to claymore the eord roomba.
  modular_RUtgmc/code/game/objects/machinery/bots/roomba.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine

#263 [Modular] add some things in med Cargo
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Feature, Test Merge Candidate, Balance, Marine, Needs testing

#259 [Not Modular] New mask of light
  code/datums/components/overlay_lighting.dm
  icons/effects/light_overlays/light_384.dmi
  icons/effects/light_overlays/light_416.dmi
  icons/effects/light_overlays/light_448.dmi
  icons/effects/light_overlays/light_480.dmi
  icons/effects/light_overlays/light_512.dmi
  icons/effects/light_overlays/light_544.dmi
  icons/effects/light_overlays/light_576.dmi
  icons/effects/light_overlays/light_608.dmi
  icons/effects/light_overlays/light_640.dmi
  icons/effects/light_overlays/light_672.dmi
  icons/effects/light_overlays/light_704.dmi
  icons/effects/light_overlays/light_736.dmi
  icons/effects/light_overlays/light_768.dmi
  icons/effects/light_overlays/light_800.dmi
  icons/effects/light_overlays/light_832.dmi
  icons/effects/light_overlays/light_864.dmi
  icons/effects/light_overlays/light_896.dmi
  icons/effects/light_overlays/light_928.dmi
  modular_RUtgmc/code/datums/components/overlay_lighting.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Sprites

#269 Xenomorph Rank Playtime Lowered
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Xeno, Quality of life

#271 Purple sprites for mini-icon state of t-gas grenades and box of t-gas grenades.
  modular_RUtgmc/code/game/objects/items/explosives/marines.dm
  modular_RUtgmc/icons/obj/items/items_mini.dmi
  modular_RUtgmc/icons/obj/items/storage/storage_boxes.dmi
Labels: Marine, Sprites

#274 Leadership button in hive status is now grey if caste can't be a leader.
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Xeno, Quality of life

#270 Lowers the acid well placing price from 400 to 300.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance, Xeno

#272 Phosphorus trailblazers to leaders vendor + fulton isn't recommended
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/items/storage/boxes.dm
Labels: Balance, Marine

#278 Revolving rifle packet for crash and vallhalla and some file moving.
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/magazines/magazines.dm
  modular_RUtgmc/code/modules/projectiles/magazines/misc.dm
  modular_RUtgmc/includes.dm
Labels: Refactor

#287 QoL Chemistry Changes
  code/__DEFINES/colors.dm
  code/modules/reagents/reagents/medical.dm
  modular_RUtgmc/code/game/objects/items/reagent_containers/autoinjectors.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/reagents/reactions/medical.dm
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance, Marine, Quality of life

#258 Gluck's Stuff + other stuff
  code/__DEFINES/loadout.dm
  modular_RUtgmc/code/game/objects/items/misc.dm
  modular_RUtgmc/code/game/objects/items/storage/backpack.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/game/objects/machinery/vending/new_marine_vendors.dm
  modular_RUtgmc/code/modules/client/preferences_gear.dm
  modular_RUtgmc/code/modules/clothing/glasses/glasses.dm
  modular_RUtgmc/code/modules/clothing/gloves/marine_gloves.dm
  modular_RUtgmc/code/modules/clothing/head/head.dm
  modular_RUtgmc/code/modules/clothing/masks/gasmask.dm
  modular_RUtgmc/code/modules/clothing/shoes/marine_shoes.dm
  modular_RUtgmc/code/modules/clothing/under/marine_uniform.dm
  modular_RUtgmc/icons/mob/clothing/back.dmi
  modular_RUtgmc/icons/mob/clothing/feet.dmi
  modular_RUtgmc/icons/mob/clothing/hands.dmi
  modular_RUtgmc/icons/mob/clothing/headwear/marine_hats.dmi
  modular_RUtgmc/icons/mob/clothing/mask.dmi
  modular_RUtgmc/icons/mob/clothing/uniforms/marine_uniforms.dmi
  modular_RUtgmc/icons/mob/human_races/r_vatborn.dmi
  modular_RUtgmc/icons/mob/human_races/r_vatgrown.dmi
  modular_RUtgmc/icons/mob/modular/modular_helmet_storage.dmi
  modular_RUtgmc/icons/obj/clothing/glasses.dmi
  modular_RUtgmc/icons/obj/clothing/gloves.dmi
  modular_RUtgmc/icons/obj/clothing/headwear/hats.dmi
  modular_RUtgmc/icons/obj/clothing/masks.dmi
  modular_RUtgmc/icons/obj/clothing/shoes/marine_shoes.dmi
  modular_RUtgmc/icons/obj/clothing/uniform.dmi
  modular_RUtgmc/icons/obj/items/priest.dmi
  modular_RUtgmc/icons/obj/items/storage/storage.dmi
  modular_RUtgmc/includes.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
Labels: Feature, Marine, Sprites

#279 Unset_interaction for xenos on move()
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Test Merge Candidate, Refactor

#288 Attack_ghost for sentries
  modular_RUtgmc/code/modules/projectiles/sentries.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine

#293 Artillery impact table to engineer vendors
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/items/storage/holsters.dm
Labels: Fix, Marine, Quality of life

#294 Keybindings for panther + hugger
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Fix, Xeno, Coding

#296 Xeno Rank Huds Fix
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix, Xeno

#257 Puppteer sprite update + balance tweak
  code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/icons/Xeno/castes/puppeteer.dmi
  modular_RUtgmc/includes.dm
Labels: Balance, Xeno, Sprites, Needs testing

#302 Keybinding for panther reagent select.
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Xeno, Quality of life

#280 [MODULAR] add tech satchel for all
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature, Marine

#299 [MODULAR] HMG changes
  modular_RUtgmc/code/modules/projectiles/guns/mounted.dm
  modular_RUtgmc/code/modules/projectiles/mounted.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine, Quality of life

#298 Changes acid well sticky grenades handling, acid well smoke now extinguishes and slight phosphorus trailblazer nerf.
  modular_RUtgmc/code/game/objects/effects/effect_system/smoke.dm
  modular_RUtgmc/code/game/objects/items/explosives/marines.dm
  modular_RUtgmc/code/modules/xenomorph/xeno_structures.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Balance, Xeno, Marine, Coding

#303 Minimap icons for flowers and wraith portals. Also fixed locator icon.
  modular_RUtgmc/code/controllers/subsystem/minimaps.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  modular_RUtgmc/code/modules/xenomorph/xeno_structures.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/includes.dm
Labels: Feature, Sprites

#300 [MODULAR] sg-62 changes
  code/__DEFINES/loadout.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
Labels: Balance, Marine
