Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2023-11, with the labels that each got.

#85 Blip Fix ?
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#127 Better-Jager-Visual
  icons/mob/modular/modular_armor_modules.dmi
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Marine, Sprites

#136 Adds impact grenade as default ammo type for PMC leader's rifle. [Modular]
  modular_RUtgmc/code/modules/projectiles/guns/grenade_launchers.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine

#141 [FIX][MODULAR] add icon for missing icon som_knife
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
  modular_RUtgmc/code/modules/projectiles/gun_attachables.dm
  modular_RUtgmc/icons/Marine/marine-weapons.dmi
  modular_RUtgmc/icons/obj/items/weapons.dmi
Labels: Fix, Marine, Sprites

#149 Фикс навыков SMARTGUN и SWORDPLAY при уроне мозгу
  code/datums/skills.dm
Labels: Fix, Marine

#150 [MODULAR] Chemistry Minor Update
  code/modules/reagents/reagents/medical.dm
  modular_RUtgmc/code/game/objects/items/reagent_containers/autoinjectors.dm
  modular_RUtgmc/code/game/objects/items/reagent_containers/glass/bottle.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/game/objects/machinery/vending/vending_types.dm
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Feature, Balance, Marine

#142 Убирает общий КД у флинга и граба Шрайка
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Controversial, Balance, Xeno

#148 [MODULAR] FIX XRAY STACKS
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/modules/projectiles/guns/energy.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Fix, Balance, Marine

#119 Barricades Rework [SEMI-MODULAR]
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/barricade.dm
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
  icons/Marine/barricades.dmi
  icons/Marine/remotefob.dmi
  modular_RUtgmc/code/game/objects/items/sheets/sheet_types.dm
  modular_RUtgmc/code/game/objects/structures/barricade.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Changes requested, Balance, Marine, Sprites

#144 [MODULAR] Fulton changes
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
  modular_RUtgmc/code/modules/requisitions/fulton.dm
  modular_RUtgmc/includes.dm
Labels: Merge Conflict, Balance, Marine

#151 Adds strappable element for entrenching tool.
  modular_RUtgmc/code/game/objects/items/tools/shovel_tools.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine

#152 [MODULAR] No More Synap + Arithr
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
Labels: Fix, Balance, Marine

#146 [MODULAR] Returns t500 to vendor with weapons
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Fix, Feature, Marine

#124 Buff scout cloak [NON-MODULAR]
  code/__DEFINES/objects.dm
Labels: Test Merge Candidate, Balance, Marine

#130 Forbid changes
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Feature, Test Merge Candidate, Xeno

#153 SL Vendor Updates
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/_defines_include.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
Labels: Feature, Changes requested, Balance, Marine

#158 Скидки на мины
  code/__DEFINES/loadout.dm
Labels: Balance, Marine

#172 [FIX][MODULAR] Fix-chemrettes
  modular_RUtgmc/code/game/objects/items/storage/fancy.dm
  modular_RUtgmc/includes.dm
Labels: Fix

#129 Allows to change how much hair the helmet is concealing. [Modular]
  modular_RUtgmc/code/modules/clothing/modular_armor/modular.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Marine, Needs testing, Coding

#139 Maybe fix of box som modules [Modular]
  modular_RUtgmc/icons/mob/modular/modular_armor_modules.dmi
Labels: Fix, Needs testing

#175 Adds sticky and trailblazer grenade boxes to cargo vendor. [Modular]
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Marine

#176 T21 extended magazine fix
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
Labels: Fix

#179 [MODULAR] Laser carbine tweak
  modular_RUtgmc/code/modules/projectiles/guns/energy.dm
Labels: Balance, Marine

#160 [FIX][MODULAR] Allow beret's for robot
  modular_RUtgmc/code/game/objects/items/tools/cleaning_tools.dm
  modular_RUtgmc/code/modules/clothing/head/collectable.dm
  modular_RUtgmc/code/modules/clothing/head/head.dm
  modular_RUtgmc/code/modules/clothing/head/jobs.dm
  modular_RUtgmc/code/modules/clothing/head/misc.dm
  modular_RUtgmc/code/modules/clothing/head/soft_caps.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/style_line.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Feature, Test Merge Candidate, Marine

#164 FC Updates
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/datums/skills.dm
  modular_RUtgmc/code/game/objects/items/weapons/twohanded.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Feature, Balance, Marine

#166 [FIX][MODULAR] Fix icon's for belts
  modular_RUtgmc/code/game/objects/items/storage/holsters.dm
  modular_RUtgmc/icons/mob/clothing/belt.dmi
  modular_RUtgmc/icons/mob/suit_slot.dmi
  modular_RUtgmc/icons/obj/clothing/belts.dmi
Labels: Fix, Marine

#167 Some changes to destroying heart with sharp tools process. [Modular]
  code/modules/mob/living/carbon/human/human_defense.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/human_defense.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Marine, Coding

#184 [FIX][MODULAR]Fix-T500-Rails
  modular_RUtgmc/code/modules/projectiles/guns/revolvers.dm
Labels: Fix, Test Merge Candidate
