Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-02, with the labels that each got.

#386 Prevents minions from breaking nests and killing nested hosts.
  code/__HELPERS/ai.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
Labels: Fix, Xeno

#403 Сhimera is now visible at orbit.
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
Labels: Fix, Xeno

#401 Adds sanity check for savage processing.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix, Xeno

#407 Mainship gray window and mainship windows frames sprites.
  modular_RUtgmc/code/game/objects/structures/window_frame.dm
  modular_RUtgmc/icons/obj/smooth_objects/ship_gray_window.dmi
  modular_RUtgmc/icons/obj/smooth_objects/ship_gray_window_frame.dmi
  modular_RUtgmc/icons/obj/smooth_objects/ship_window.dmi
  modular_RUtgmc/icons/obj/smooth_objects/ship_window_frame.dmi
Labels: Fix, Sprites

#367 Makes vents and pipes crushable by shuttle.
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/pipes/pipes.dm
  modular_RUtgmc/includes.dm
Labels: Feature

#385 Moves smart pistol from vendor with SG guns to vendor with free choices.
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
Labels: Balance, Marine, Quality of life

#382 behemoth wrath issues
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix

#391 Adds backpacks to gear customisation.
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/jobs/job/job.dm
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
Labels: Feature, Marine

#357 [MODULAR] Praetorian
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Balance, Xeno

#406 [MODULAR] MG-100 buff?
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/modules/projectiles/guns/specialist.dm
  modular_RUtgmc/code/modules/projectiles/magazines/specialist.dm
Labels: Balance, Marine

#397 Barricades fixes and a bit of code refactor.
  code/game/objects/structures/barricade.dm
  modular_RUtgmc/code/game/objects/structures/barricade.dm
Labels: Fix, Marine

#396 KeyUp verb `null.up()` runtime fix attempt.
  code/modules/keybindings/bindings_client.dm
Labels: Fix, Optimization

#409 Adds t76 ammo packet to vendor, moves t500 to sidearms from specialized.
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/guns/revolvers.dm
  modular_RUtgmc/code/modules/projectiles/magazines/misc.dm
  modular_RUtgmc/icons/obj/items/ammo.dmi
Labels: Marine, Quality of life

#413 Fixes missing armor for ballistic goggles combined with optical imagers.
  modular_RUtgmc/code/modules/clothing/glasses/night.dm
Labels: Fix

#412 Changes advanced medical gloves sprites.
  modular_RUtgmc/code/game/objects/items/defibrillator.dm
  modular_RUtgmc/code/game/objects/items/scanners.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/includes.dm
Labels: Fix

#417 Fixes tools not giving out from loadouts in valhalla.
  code/__DEFINES/loadout.dm
Labels: Fix

#418 Fixes generators minimap blips.
  modular_RUtgmc/code/controllers/subsystem/minimaps.dm
Labels: Fix

#414 Fixes loadouts not giving out gear from gear vendors.
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#416 Comments keybind for behemoth's roll.
  code/datums/keybinding/xeno.dm
Labels: Fix, Xeno

#342 Increases silo scaling for distress, sets silo limit to 2.
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  modular_RUtgmc/code/datums/gamemodes/distress.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Changes requested, Balance, Xeno, Quality of life

#347 [SEMI-MODULAR] martini henry
  code/modules/projectiles/guns/shotguns.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/modules/projectiles/guns/shotguns.dm
Labels: Test Merge Candidate, Balance, Marine

#423 Ревёрт нерфа рапиры. Модульный!
  modular_RUtgmc/code/game/objects/items/weapons/harvester.dm
Labels: Balance, Marine

#404 Puppeteer QOL
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
Labels: Test Merge Candidate, Xeno, Coding, Quality of life

#410 Surgery sounds
  code/modules/surgery/amputation.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/headreattach.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/internal_bleeding.dm
  code/modules/surgery/necrosis.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/robolimbs.dm
  code/modules/surgery/surgery.dm
  modular_RUtgmc/sound/misc/surgery/acid_sizzle2.ogg
  modular_RUtgmc/sound/misc/surgery/bandage.ogg
  modular_RUtgmc/sound/misc/surgery/cautery1.ogg
  modular_RUtgmc/sound/misc/surgery/cautery2.ogg
  modular_RUtgmc/sound/misc/surgery/clothingrustle1.ogg
  modular_RUtgmc/sound/misc/surgery/clothingrustle5.ogg
  modular_RUtgmc/sound/misc/surgery/hemostat1.ogg
  modular_RUtgmc/sound/misc/surgery/organ1.ogg
  modular_RUtgmc/sound/misc/surgery/organ2.ogg
  modular_RUtgmc/sound/misc/surgery/retractor1.ogg
  modular_RUtgmc/sound/misc/surgery/retractor2.ogg
  modular_RUtgmc/sound/misc/surgery/saw.ogg
  modular_RUtgmc/sound/misc/surgery/scalpel1.ogg
  modular_RUtgmc/sound/misc/surgery/scalpel2.ogg
Labels: Marine, Sound, Port

#422 Xeno Wall Cool PR МОДУЛЬНЫЙ
  modular_RUtgmc/code/game/objects/structures/xeno.dm
  modular_RUtgmc/code/game/turfs/walls/resin.dm
Labels: Fix, Xeno

#336 [Modular] Minor med cargo rebalance
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance, Marine

#450 Jumping over glass shards.
  code/game/objects/items/shards.dm
Labels: Quality of life

#443 Makes dreadful presence plasma cost 50 again.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
Labels: Balance, Xeno

#441 Adds override = TRUE to the behemoth's cancel charge proc.
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Xeno, Optimization

#444 Lowers flare fuel limits values.
  modular_RUtgmc/code/game/objects/items/explosives/marines.dm
Labels: Balance, Marine

#445 Allows to put phosphorus trailblazers in the grenade launchers.
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Fix, Marine

#448 Fixes gorger getting blood from the dead with carnage slashes.
  code/datums/status_effects/xeno_buffs.dm
Labels: Fix

#430 [MODULAR] Knee mortar to vendor
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Marine

#415 Incision management system removal to cargo
  code/game/objects/effects/spawners/random/medical.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/surgical_tray.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance, Marine

#421 [NON-MODULAR] pickup fix
  code/game/objects/items/weapons/twohanded.dm
Labels: Fix

#419 Shotgun Pouch Buff
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/sons_of_mars_ert.dm
  code/datums/jobs/job/special_forces.dm
  code/game/objects/items/storage/pouch.dm
Labels: Balance

#426 Tweaks adrenaline a bit, makes its self sustainable reagent and not a synaptizine suptype.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
Labels: Balance

#457 Adds some ? marks to prevent knife throwing runtimes.
  code/game/objects/items/weapons/blades.dm
Labels: Optimization

#451 Makes combat med kits its own type, to avoid multiplying them with worse kits.
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/items/stacks/medical.dm
  modular_RUtgmc/code/game/objects/items/storage/belt.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Fix

#428 Plasma cutter little fixes.
  modular_RUtgmc/code/game/objects/items/tools/mining_tools.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Marine, Quality of life

#456 Adds some ? marks to minimaps code, for runtime prevention
  code/controllers/subsystem/minimaps.dm
Labels: Optimization

#340 M-sensor module for C-robot
  code/modules/clothing/modular_armor/combat_robot.dm
Labels: Fix, Changes requested, Marine

#420 [NON-MODULAR] behemoth fix, again
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix

#411 Adds a visible line when using IV drips
  code/game/objects/machinery/iv_drip.dm
  modular_RUtgmc/code/game/objects/machinery/iv_drip.dm
  modular_RUtgmc/icons/effects/beam.dmi
  modular_RUtgmc/includes.dm
Labels: Marine, Sprites, Port

#452 Adds `AMMO_SKIPS_ALIENS` flag to prae's and spitter's acid spits.
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Balance

#455 Nerfs pepperball stamina damage.
  code/modules/projectiles/guns/specialist.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Balance

#462 Makes ai controller properly clean up refs.
  code/datums/components/ai.dm
Labels: Fix

#366 Huds Major Improvements
  code/game/data_huds.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/icons/mob/hud.dmi
Labels: Feature, Sprites, Refactor, Quality of life

#461 Queen armor revert
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Labels: Balance, Xeno

#454 Fasygin removal
  code/__DEFINES/colors.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/code/game/objects/items/reagent_containers/autoinjectors.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/reagents/reactions/medical.dm
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine, Removal

#449 Сarrier buff
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance, Xeno

#463 Attack log runtime fix.
  code/__HELPERS/logging/attack.dm
Labels: Optimization

#465 Remakes how passthrough acid spits for spitters and prae's were made, so they don't touch turrets and queen.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Fix, Xeno
