Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-06, with the labels that each got.

#618 Fixes xenonauten modules icons and some reorg.
  code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/icons/mob/modular/modular_armor_modules.dmi
  modular_RUtgmc/icons/mob/modular/som_armor_modules.dmi
Labels: Fix, Sprites, Port

#594 GL-81 tacticla reload
  modular_RUtgmc/code/game/objects/items/storage/belt.dm
  modular_RUtgmc/code/modules/projectiles/guns/grenade_launchers.dm
Labels: Marine, Quality of life

#545 Renames exp_type_special to exp_type_xeno.
  code/__DEFINES/jobs.dm
  code/__DEFINES/~RUtgmc_defines/jobs.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/job_exp.dm
  code/datums/jobs/job/xenomorph.dm
Labels: Refactor

#614 Adds crash evacuation griefing admin intervention possibility.
  code/__DEFINES/~RUtgmc_defines/_defines_include.dm
  code/__DEFINES/~RUtgmc_defines/cooldowns.dm
  modular_RUtgmc/code/modules/shuttle/marine_dropship.dm
Labels: Administration

#616 Cleaned up fire sprites (#15674)
  icons/effects/fire.dmi
  modular_RUtgmc/code/modules/projectiles/guns/flamer.dm
  modular_RUtgmc/icons/effects/fire.dmi
  modular_RUtgmc/includes.dm
Labels: Sprites, Port

#621 defiler is big, tentacle is weaker
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Xeno

#632 Officer swords are now bulky.
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
Labels: Fix, Marine

#625 Carbine
  modular_RUtgmc/code/modules/projectiles/guns/energy.dm
Labels: Balance, Marine

#615 heavy armor buff (+leader helmet)
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/chest_plates.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/combat_robot.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/jaeger.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/xenonauten.dm
Labels: Balance, Marine

#628 Warrior
  code/__DEFINES/action.dm
  code/__DEFINES/actions.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/xeno_action.dm
  code/datums/keybinding/xeno.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/abilities.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Feature, Xeno, Port

#567 Adds display for job preferences if jobs are time locked.
  code/datums/jobs/job/job_exp.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_ui.dm
  modular_RUtgmc/code/datums/jobs/job/job_exp.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
Labels: Feature, Needs testing, Interface

#624 Chimera
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/chimera/castedatum_chimera.dm
Labels: Balance, Xeno

#609 Refactors ventilation `relaymove`, makes pipes immune to shuttle crush again, hopefully fixes shuttles breaking pipenets after move.
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/shuttle/on_move.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/atmosmachinery.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/datum_pipeline.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/pipes/pipes.dm
  modular_RUtgmc/code/modules/shuttle/on_move.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Refactor

#637 Makes spaceheater xenodamageable.
  modular_RUtgmc/code/game/objects/machinery/spaceheater.dm
  modular_RUtgmc/includes.dm
Labels: Fix

#638 Adds few missing grenades to vallhalla weaponry vendor.
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix, Marine

#648 Panther nerf
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Balance, Xeno

#643 Big defiler and his little friend sentinel
  code/modules/reagents/reagents/toxin.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Labels: Balance, Xeno

#646 Fixes tad breaking unhidden pipenets.
  code/modules/shuttle/on_move.dm
  modular_RUtgmc/code/modules/shuttle/on_move.dm
Labels: Fix

#645 Restricts ghosts from spam spawning huggers from carriers and eggs.
  code/__DEFINES/~RUtgmc_defines/cooldowns.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/egg.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#630 Yet another attempt to fix box modules.
  modular_RUtgmc/code/datums/components/attachment_handler.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/modular.dm
  modular_RUtgmc/icons/mob/modular/modular_armor_modules.dmi
  modular_RUtgmc/icons/mob/modular/som_armor_modules.dmi
  modular_RUtgmc/includes.dm
Labels: Fix

#654 duplicate actions fix
  modular_RUtgmc/code/modules/mob/living/carbon/human/yautja.dm
Labels: Fix

#658 CRASH-Doctor slot
  modular_RUtgmc/code/datums/gamemodes/crash.dm
Labels: Feature, Balance, Marine

#635 Ravager's vampirism now consumes a little of blood from the victim.
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance, Xeno

#650 tomahawk buff
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
Labels: Feature, Balance, Marine

#639 Erp panel and some new emotes
  modular_RUtgmc/code/modules/emotes/emote_panel.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/emote.dm
  modular_RUtgmc/includes.dm
  modular_RUtgmc/sound/misc/sound_misc_knuckles.ogg
  modular_RUtgmc/sound/voice/robotic/dwoop.ogg
  modular_RUtgmc/sound/voice/robotic/female_giggle.ogg
  modular_RUtgmc/sound/voice/robotic/female_laugh.ogg
  modular_RUtgmc/sound/voice/robotic/female_medic.ogg
  modular_RUtgmc/sound/voice/robotic/male_giggle.ogg
  modular_RUtgmc/sound/voice/robotic/male_laugh_1.ogg
  modular_RUtgmc/sound/voice/robotic/male_laugh_2.ogg
  modular_RUtgmc/sound/voice/robotic/male_medic.ogg
  modular_RUtgmc/sound/voice/robotic/male_medic2.ogg
  modular_RUtgmc/sound/voice/robotic/sitcomLaugh1.ogg
  modular_RUtgmc/sound/voice/robotic/sitcomLaugh2.ogg
  modular_RUtgmc/sound/voice/robotic/synth_no.ogg
  modular_RUtgmc/sound/voice/robotic/synth_yes.ogg
  modular_RUtgmc/sound/voice/robotic/twobeep.ogg
  modular_RUtgmc/sound/voice/sound_voice_human_whistle1.ogg
Labels: Feature, Sound, Interface

#636 Makes disposal bins xenodamageable.
  modular_RUtgmc/code/modules/recycling/disposal.dm
Labels: Balance

#651 Fixes shield not blocking pounces #14861, also cleans up facehugger pounce code.
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/facehugger/facehugger.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/predalien/abilities_predalien.dm
Labels: Fix, Refactor

#662 Fixes xenos not being able to attack in the head.
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Fix
