Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-03, with the labels that each got.

#393 tail swep feature
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Feature, Balance, Xeno, Needs testing

#468 Fixes runtimes from gibbing the mob with ai and player.
  code/datums/components/ai.dm
Labels: Optimization

#460 Vendor rebalance partly revert
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/structures/teleporter.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine

#469 Proper crusher crest toss toggling.
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  modular_RUtgmc/icons/Xeno/actions.dmi
Labels: Xeno, Quality of life

#471 Synth vendor buff
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  modular_RUtgmc/code/game/objects/items/cards_ids.dm
  modular_RUtgmc/includes.dm
Labels: Balance

#489 Adds ? to bottles `update_icon` to prevent runtimes.
  modular_RUtgmc/code/game/objects/items/reagent_containers/glass/bottle.dm
Labels: Optimization

#486 Fixes minimap drawing logging into unexisting category.
  code/modules/logging/categories/log_category_game.dm
Labels: Optimization

#487 Adds early return to the runtiming part of sentry code.
  code/modules/projectiles/sentries.dm
Labels: Optimization

#477 Xenos can no longer open boxes
  code/game/objects/items/storage/storage.dm
Labels: Fix, Xeno

#491 Shrike cannot deevolve
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Feature, Xeno

#394 Warlock unfuck
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/warlock.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Feature, Test Merge Candidate, Balance, Xeno, Needs testing, Coding

#447 Baneling removed. New minion: baneling.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/Xeno/castes/baneling.dmi
  modular_RUtgmc/code/_globalvars/lists/mobs.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
Labels: Feature, Xeno

#475 AP bullets
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance, Marine, Needs testing

#483 Acid cone buff
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Balance, Xeno

#478 synth vendor
  modular_RUtgmc/code/game/objects/items/cards_ids.dm
Labels: Balance, Marine

#501 Fixes world time.
  code/game/world.dm
Labels: Fix, Coding

#470 Minimap body indicator fix, some health huds sprite and code changes.
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  code/game/data_huds.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/radio/headset.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/code/game/objects/items/radio/headset.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/human_defines.dm
  modular_RUtgmc/icons/mob/hud.dmi
Labels: Fix, Needs testing

#511 Fixes sg62 supply crate spawning nothing.
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Fix, Marine, Coding

#484 Fixes huggers duplicating from eggs.
  code/modules/mob/living/carbon/xenomorph/egg.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/egg.dm
Labels: Fix, Xeno, Coding

#498 Makes alerts bouncy.
  code/_onclick/hud/alerts.dm
Labels: Feature, Interface

#507 T500 holster fixes and tweaks.
  modular_RUtgmc/code/game/objects/items/storage/belt.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/icons/obj/clothing/belts.dmi
Labels: Fix

#424 Второе пришествие быка (bull rework v2)
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Feature, Balance, Xeno, Needs testing, Coding

#506 Adds unique action for hyposprays.
  modular_RUtgmc/code/game/objects/items/reagent_containers/hypospray.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Coding

#500 SG-62, again
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
Labels: Balance, Marine, Needs testing

#466 Neurotoxin removal
  code/__DEFINES/xeno.dm
  code/__DEFINES/~RUtgmc_defines/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  modular_RUtgmc/icons/Xeno/actions_boiler_glob.dmi
  modular_RUtgmc/includes.dm
Labels: Balance, Xeno, Coding, Removal

#499 Incend slug buff
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Balance, Marine, Needs testing

#516 Anesthetic autoinjector removal.
  modular_RUtgmc/code/game/objects/machinery/vending/vending_types.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Removal

#502 Adds unique action for medevac.
  modular_RUtgmc/code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Feature, Coding

#509 Fixes acid on boxes not triggering upon pickup.
  code/game/objects/items/storage/boxes.dm
  modular_RUtgmc/code/game/objects/items/storage/boxes.dm
Labels: Fix, Coding

#513 Adds synth and fc categories to the loadout vendor, also fixes that essentials wasn't giving out for them.
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  modular_RUtgmc/code/game/objects/machinery/vending/new_marine_vendors.dm
  tgui/packages/tgui/interfaces/LoadoutManager/index.tsx
Labels: Feature, Coding

#521 Add neuraline to cargo
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance

#526 Слои для миникарты (#15316)
  code/__DEFINES/layers.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/computer/nt_access.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/structures/campaign_structures/campaign_structure.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  code/game/objects/structures/sensor_tower.dm
  code/game/objects/structures/teleporter.dm
  code/modules/events/intel_computer.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix, Port, Quality of life

#535 Gives bayonets old sprites.
  modular_RUtgmc/code/modules/projectiles/gun_attachables.dm
  modular_RUtgmc/icons/Marine/marine-weapons.dmi
  modular_RUtgmc/icons/obj/items/weapons.dmi
Labels: Marine, Sprites

#528 Исправлены лодауты профессий в Валгалле. (#15107)
  code/__DEFINES/loadout.dm
  code/datums/loadout/loadout_helper.dm
Labels: Fix, Port

#527 Манифест улья (#15128)
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/datums/datacore.dm
  code/modules/mob/new_player/new_player.dm
  modular_RUtgmc/code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Interface, Port

#533 Deletes modular copy `/datum/controller/subsystem/minimaps/Initialize()`, cherry picks upstream version properly.
  code/controllers/subsystem/minimaps.dm
  modular_RUtgmc/code/controllers/subsystem/minimaps.dm
Labels: Fix, Port

#515 Коробки для патрон дробовика весят меньше
  code/game/objects/items/storage/pouch.dm
  code/modules/projectiles/magazines/shotguns.dm
Labels: Balance, Marine

#488 Acid dash changes + xeno charge fixes
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Labels: Balance, Xeno, Needs testing

#479 Makes crest toss 2 separate abilities with shared cooldown.
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Feature, Xeno, Quality of life

#542 Shrike
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance, Xeno

#541 Ravager
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance, Xeno

#519 Organ damage rng
  code/modules/organs/limbs.dm
Labels: Balance

#514 Blessings changes
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance, Xeno
