Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-01, with the labels that each got.

#277 [NO MODULAR] Fix robo backpack
  icons/mob/species/robot/backpack.dmi
Labels: Fix, Do Not Merge, Marine, Sprites

#317 Ё
  code/_globalvars/admin.dm
Labels: Fix

#308 Removes larva ranks
  code/game/data_huds.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
Labels: Fix, Feature, Xeno

#312 [MODULAR] Puppeteer Nerf
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
Labels: Balance, Xeno

#304 Fixes bodybag welding and closet contents deletion upon welding.
  code/game/objects/structures/crates_lockers/closets.dm
  modular_RUtgmc/code/game/objects/items/bodybag.dm
  modular_RUtgmc/code/game/objects/structures/crates_lockers/closets.dm
  modular_RUtgmc/includes.dm
Labels: Fix, Marine

#323 Suppressor Refactor
  modular_RUtgmc/code/modules/projectiles/gun_attachables.dm
Labels: Balance, Marine, Refactor

#322 [MODULAR] XENO_DAMAGEABLE flag for mortars
  modular_RUtgmc/code/game/objects/machinery/mortar.dm
Labels: Feature, Balance, Marine

#319 [MODULAR] juggle
  code/controllers/subsystem/persistence.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#326 Fixes chem master do_after
  code/modules/reagents/machinery/chem_master.dm
Labels: Fix, Changes requested, Marine

#333 Update slurring_drunk_text.json
  strings/slurring_drunk_text.json
Labels: Marine, Quality of life

#339 Restricts psylance before shutters.
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Fix

#344 Fixes chem dispenser's `do_after`
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Fix, Marine

#341 Chimera keybindings tweaks, also inject gas keybind fix.
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/chimera/abilities_chimera.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Fix, Xeno, Quality of life

#328 Vendors Balance Changes + Visual Improvements
  code/__DEFINES/loadout.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  modular_RUtgmc/code/game/objects/machinery/vending/new_marine_vendors.dm
  modular_RUtgmc/code/game/objects/structures/teleporter.dm
  tgui/packages/tgui/interfaces/MarineSelector.js
Labels: Feature, Balance, Marine, Needs testing, Refactor, Interface, Quality of life

#292 Widow removal
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/keybinding/xeno.dm
  code/modules/admin/topic.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/widow.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
  modular_RUtgmc/code/_globalvars/lists/mobs.dm
  modular_RUtgmc/code/modules/admin/panels/player_panel.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/includes.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Feature, Balance, Xeno, Needs testing, Coding

#335 [Modular] Fix Cargo Mortar tangle Shell
  code/modules/reqs/supplypacks.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Fix, Marine

#356 Fixes panther heart sprite
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
Labels: Fix, Xeno, Sprites

#355 Unlimited Derringers
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Marine

#350 Deletes warlock immobilizing for psychic blast.
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance, Xeno

#352 SH-46 Combat Shotgun
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/modules/projectiles/guns/shotguns.dm
  modular_RUtgmc/icons/Marine/gun64.dmi
  modular_RUtgmc/icons/mob/clothing/back.dmi
  modular_RUtgmc/icons/mob/items_lefthand_1.dmi
  modular_RUtgmc/icons/mob/items_righthand_1.dmi
  modular_RUtgmc/icons/mob/suit_slot.dmi
  modular_RUtgmc/sound/weapons/guns/shotgun/SH-46/SH46.ogg
  modular_RUtgmc/sound/weapons/guns/shotgun/SH-46/SH46_boltpull.ogg
  modular_RUtgmc/sound/weapons/guns/shotgun/SH-46/SH46_shell.ogg
Labels: Feature, Balance, Marine, Sprites

#343 Queen Nerf
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Labels: Balance, Xeno

#334 Adds config flags for spam messages from tgs messaging.
  code/__HELPERS/admin.dm
  code/modules/client/client_procs.dm
  config/config.txt
  modular_RUtgmc/code/controllers/configuration/entries/general.dm
  modular_RUtgmc/includes.dm
Labels: Feature, Test Merge Candidate, Do Not Merge, Quality of life, Config

#361 Tomahawk + Machete buff
  modular_RUtgmc/code/game/objects/items/storage/holsters.dm
  modular_RUtgmc/code/game/objects/items/weapons/blades.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/icons/mob/clothing/back.dmi
  modular_RUtgmc/icons/mob/inhands/weapons/melee_left.dmi
  modular_RUtgmc/icons/mob/inhands/weapons/melee_right.dmi
  modular_RUtgmc/icons/mob/suit_slot.dmi
  modular_RUtgmc/icons/obj/items/storage/storage.dmi
  modular_RUtgmc/icons/obj/items/weapons.dmi
  modular_RUtgmc/sound/weapons/melee/knife_in.ogg
  modular_RUtgmc/sound/weapons/melee/knife_out.ogg
Labels: Feature, Test Merge Candidate, Balance, Marine, Sprites

#306 [MODULAR] Crusher
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance, Xeno, Needs testing

#370 Supply beacon runtime fix.
  code/game/objects/machinery/squad_supply/supply_beacon.dm
Labels: Fix

#369 Stun mitigation component runtime fix, probably.
  code/datums/components/stun_mitigation.dm
Labels: Fix

#365 Adds extinguishing gas to acid well on ignition.
  modular_RUtgmc/code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#373 Fasygin overdose threshold FIX
  modular_RUtgmc/code/modules/reagents/reagents/medical.dm
Labels: Fix, Marine

#377 Preround resinbuilding runtime fix
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#368 Xeno pull speed fix.
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix, Xeno, Optimization

#309 Silo collapse for hive status
  code/modules/admin/panels/mode_panel.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Xeno, Coding, Interface

#374 Changes sprites for colony windows to older ones.
  modular_RUtgmc/code/game/objects/structures/window.dm
  modular_RUtgmc/code/game/objects/structures/window_frame.dm
  modular_RUtgmc/icons/obj/smooth_objects/col_window.dmi
  modular_RUtgmc/icons/obj/smooth_objects/col_window_frame.dmi
Labels: Sprites

#380 no more T-Gas for FK
  code/__DEFINES/~RUtgmc_defines/loadout.dm
Labels: Balance, Marine

#378 Fixes gorger carnage runtime
  modular_RUtgmc/code/datums/status_effects/xeno_buffs.dm
Labels: Fix

#389 Allows to use king's laser and warlock's penetrating psylance if the tad or pod lands on ground.
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Quality of life

#384 Fixes icons in orbit.
  code/_globalvars/lists/flavor_misc.dm
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
Labels: Fix

#383 Adds null check for shuttle id warnings.
  code/controllers/subsystem/shuttle.dm
Labels: Fix, Optimization

#398 Modular `do_after`'s update.
  modular_RUtgmc/code/game/objects/items/tools/soldering_tool.dm
  modular_RUtgmc/code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  modular_RUtgmc/code/game/objects/structures/xeno.dm
  modular_RUtgmc/code/game/turfs/walls/resin.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  modular_RUtgmc/code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  modular_RUtgmc/code/modules/mob/living/carbon/human/human_defense.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/facehugger/abilities_facehugger.dm
Labels: Fix
