Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-05, with the labels that each got.

#565 Tiers scaling
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance, Xeno, Needs testing

#548 Baneling removal
  code/__DEFINES/action.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/xenomorph/xeno_structures.dm
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  modular_RUtgmc/includes.dm
  tgmc.dme
Labels: Balance, Xeno, Removal

#605 Few tweaks to carrier and hugger egg `attack_ghost`
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/egg.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Xeno, Refactor

#601 Laser snipe nerf
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Balance, Marine

#595 front armor removal
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Labels: Balance, Xeno, Removal

#596 heal creech removal
  code/__DEFINES/~RUtgmc_defines/dsc/signals.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance, Xeno, Removal

#607 cargo qol
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/code/modules/reqs/supply.dm
Labels: Balance, Marine, Quality of life

#612 Reverts reqtorio pizza prices.
  modular_RUtgmc/code/modules/factory/howtopaper.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
  modular_RUtgmc/code/modules/requisitions/supply_export.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine

#617 Some cleaning and a little fix for orange glasses.
  modular_RUtgmc/code/modules/clothing/glasses/glasses.dm
  modular_RUtgmc/icons/mob/clothing/eyes.dmi
  modular_RUtgmc/icons/obj/clothing/glasses.dmi
Labels: Fix, Sprites

#613 A bit of cleaning for motion detector module.
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix, Refactor

#608 Tweaks how drop keybind works slightly.
  code/datums/keybinding/mob.dm
  modular_RUtgmc/code/datums/keybinding/mob.dm
  modular_RUtgmc/includes.dm
Labels: Fix

#604 Fixes `attack_ghost` for teleporter.
  code/game/objects/structures/teleporter.dm
  modular_RUtgmc/code/game/objects/structures/teleporter.dm
  modular_RUtgmc/includes.dm
Labels: Xeno, Refactor

#603 Pocket beam attachment
  code/modules/projectiles/guns/rifles.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/modules/projectiles/guns/energy.dm
  modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
  modular_RUtgmc/code/modules/projectiles/guns/smgs.dm
  modular_RUtgmc/icons/Marine/marine-weapons.dmi
Labels: Feature, Marine, Needs testing

#619 Fixes welding module keeping the eye protection on the helmet on detach.
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix, Marine

#602 Siderms storage buff
  modular_RUtgmc/code/game/objects/items/storage/holsters.dm
  modular_RUtgmc/code/game/objects/items/storage/pouch.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/uniform.dm
  modular_RUtgmc/includes.dm
Labels: Balance, Marine, Quality of life

#600 Med rig and lifesaver buff
  code/game/objects/items/storage/belt.dm
Labels: Balance, Marine

#597 No stealth hijack
  modular_RUtgmc/code/modules/shuttle/marine_dropship.dm
Labels: Balance, Xeno, Marine
