Repository Cosmic-Overlord/RU-TerraGov-Marine-Corps, pull requests merged in 2024-04, with the labels that each got.

#561 Behemoth
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  icons/effects/effects.dmi
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  modular_RUtgmc/includes.dm
  sound/effects/behemoth/seismic_fracture_landing.ogg
Labels: Feature, Balance, Xeno, Coding, Port

#539 Short acid spray for prae... and more
  code/__DEFINES/dcs/signals.dm
  modular_RUtgmc/code/datums/keybinding/xeno.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Feature, Balance, Xeno

#557 Fixes balloon alert for king's primo laser use attempts before shutters are open. (#14799)
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Fix

#553 Cleans up imperial guardsman ert code. (#14702)
  code/datums/jobs/job/imperium.dm
  icons/mob/clothing/suits/ert_suits.dmi
  icons/obj/clothing/suits/ert_suits.dmi
Labels: Refactor

#556 Tweaks health in status tab. (#14764)
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Refactor

#562 Restricts ravagers gaining plasma from the fire tiles they don't take damage from.
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Fix

#551 Panther abilities code cleanup.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Refactor

#555 Attack_ai for maptable. (#14735)
  code/game/objects/machinery/cic_maptable.dm
Labels: Refactor

#558 Fixes xenos with non-standard wound handling not showing wounds in special states. [#15056]
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
Labels: Fix

#524 Хаггеры правильно приоритезируют свою цель (#15370)
  code/__DEFINES/_math.dm
  code/__HELPERS/math.dm
  code/controllers/subsystem/advanced_pathfinding.dm
  code/controllers/subsystem/weeds.dm
  code/game/atoms_movable.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/machinery/mortar.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
Labels: Fix, Xeno, Coding

#563 Projectiles with `AMMO_PASS_THROUGH_MOVABLE` now don't go through lz shutters.
  code/__DEFINES/~RUtgmc_defines/is_helpers.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#559 Replaces some unneeded cases of `span_boldannounce` to `span_danger` (#15180)
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/modules/reagents/reagents.dm
Labels: Refactor

#573 Free smartgun ammo for crash
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Marine

#572 Allows robots to wear martin and bomb vests.
  modular_RUtgmc/code/game/objects/items/explosives/bombvest.dm
  modular_RUtgmc/code/modules/clothing/head/misc.dm
Labels: Marine

#485 The Great Armor Changes
  code/__DEFINES/loadout.dm
  code/__DEFINES/objects.dm
  code/__DEFINES/~RUtgmc_defines/_defines_include.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  code/__DEFINES/~RUtgmc_defines/objects.dm
  code/datums/components/suit_autodoc.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/factory/parts.dm
  code/modules/reqs/supplypacks.dm
  modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
  modular_RUtgmc/code/game/objects/machinery/vending/new_marine_vendors.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/chest_plates.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/combat_robot.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/jaeger.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/som.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/xenonauten.dm
  modular_RUtgmc/code/modules/reqs/supplypacks.dm
Labels: Balance, Marine, Needs testing, Removal

#520 HUDs Improvements #2
  code/__DEFINES/~RUtgmc_defines/atom_hud.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/power/groundmap_geothermal.dm
  modular_RUtgmc/code/game/data_huds.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  modular_RUtgmc/icons/UI_Icons/map_blips.dmi
  modular_RUtgmc/icons/mob/hud.dmi
Labels: Feature, Sprites, Coding, Interface

#536 Adds new effects for xeno turrets on destruction that aren't acidic.
  code/modules/xenomorph/xeno_structures.dm
  modular_RUtgmc/code/modules/xenomorph/xeno_structures.dm
Labels: Feature, Xeno, Coding

#531 Очки ночного зрения (#14984)
  code/__DEFINES/traits.dm
  code/__DEFINES/~RUtgmc_defines/loadout.dm
  code/_onclick/click.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery/cell_charger.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/mark_one.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/power/cell.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/clothing/eyes.dmi
  icons/mob/modular/modular_armor_modules.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/power.dmi
  sound/items/scan_pulse.wav
Labels: Feature, Balance, Marine, Port

#579 Crusher fix (#15226)
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#574 Fixes artillery not working.
  code/game/objects/machinery/mortar.dm
Labels: Fix

#564 widescreen and fixes
  code/__DEFINES/~RUtgmc_defines/_defines_include.dm
  code/__DEFINES/~RUtgmc_defines/preferences.dm
  code/controllers/configuration/entries/general.dm
  code/datums/view.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/login.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/shuttle/navigation_computer.dm
  config/config.txt
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Feature, Interface, Port, Quality of life, Config

#577 СЛ больше не может купить скаут плащ
  code/__DEFINES/~RUtgmc_defines/loadout.dm
Labels: Balance, Marine

#575 Scatter spit
  modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
Labels: Balance, Xeno

#453 Puppeteer removal
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/xeno.dm
  code/__DEFINES/~RUtgmc_defines/xeno.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/admin/topic.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/abilities_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums.dm
  modular_RUtgmc/code/_globalvars/lists/flavor_misc.dm
  modular_RUtgmc/code/_globalvars/lists/mobs.dm
  modular_RUtgmc/code/modules/admin/panels/player_panel.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  modular_RUtgmc/includes.dm
Labels: Controversial, Xeno, Removal

#497 Ryetalyn's death
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/reactions/medical.dm
  modular_RUtgmc/code/modules/reagents/reactions/medical.dm
Labels: Balance, Marine, Removal

#585 Adds proper icons for corpsman backpack on lower charge values.
  modular_RUtgmc/code/game/objects/items/storage/backpack.dm
  modular_RUtgmc/icons/mob/clothing/back.dmi
  modular_RUtgmc/icons/mob/inhands/equipment/backpacks_left.dmi
  modular_RUtgmc/icons/mob/inhands/equipment/backpacks_right.dmi
  modular_RUtgmc/icons/obj/items/storage/storage.dmi
Labels: Fix, Sprites

#588 xenonauten helmet
  modular_RUtgmc/code/modules/clothing/modular_armor/xenonauten.dm
Labels: Fix

#576 Prevents deevolve punishment from deleting xenos in different stances.
  modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#580 artemis buff
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance, Marine

#587 Adds sanity checks for motion detectors blips.
  code/game/objects/items/motion_detector.dm
  modular_RUtgmc/code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Optimization

#583 Tad can no longer perform instant transmission (#15091)
  code/modules/shuttle/mini_dropship.dm
Labels: Fix

#571 Fixes time offsets.
  code/__HELPERS/time.dm
  code/game/world.dm
Labels: Fix
